onlyBuiltDependencies:
  - esbuild
  - sharp
overrides:
  brace-expansion@>=5.0.0 <5.0.6: '>=5.0.6'
  fast-xml-builder@<=1.1.6: '>=1.1.7'
  fast-xml-builder@=1.1.5: '>=1.1.6'
  tmp@<0.2.6: '>=0.2.6'
  tmp@<=0.2.3: '>=0.2.4'
