allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - "@rolldown/binding-darwin-x64@1.2.8"
  - "@rolldown/binding-freebsd-x64@1.2.8"
  - "@rolldown/binding-linux-x64-gnu@1.2.8"
  - "@rolldown/binding-openharmony-arm64@1.2.8"
  - "@rolldown/binding-win32-x64-msvc@1.2.8"
overrides:
  astro@<7.2.8: ^7.2.8
  deepmerge-ts@<8.0.0: ^8.0.0
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  sharp@<0.35.4: ^0.35.4
  svgo@>=4.0.0 <4.1.0: ^4.1.0
  tmp@<0.2.6: ^0.2.6
